### ISSUE TITLE
Does not pass method annotations to Description

### ISSUE THREAD

**Issue by niom** [havarunner/havarunner#12]
Annotations are not passed to Description object and there for trying to match to annotations in TestRule is impossible.

Apparently the problem lies in RunnerHelper.describeTest

**Comment by laurilehmijoki** [comment]
Can you give an example in Java code?

ke 23. marraskuuta 2016 klo 8.41 niom <notifications@github.com> kirjoitti:

**Comment by niom** [comment]
Here you go:

When using HavaRunner as the test runner this just fails and the annotation is never matched.
When using JUnit4 as the test runner this will end to the assumption and have ignored state.

´´´
import com.github.havarunner.HavaRunner;
import org.junit.Assume;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestRule;
import org.junit.runner.Description;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;
import org.junit.runners.model.Statement;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

import static org.junit.Assert.fail;

@RunWith(HavaRunner.class)
public class NoAnnotations {

    @Rule
    public SomeTestRule testRule = new SomeTestRule();

    @Test
    @RunOnlyWhenPropertyEnabled
    public void someTest() {
        fail("Should not run");
    }

    @Retention(RetentionPolicy.RUNTIME)
    @Target({ElementType.METHOD})
    public @interface RunOnlyWhenPropertyEnabled {}

    public static class SomeTestRule implements TestRule {
        public Statement apply(Statement base, Description description ) {
            if(description.getAnnotation(RunOnlyWhenPropertyEnabled.class) != null) {
                return new Statement() {
                    @Override
                    public void evaluate() throws Throwable {
                        Assume.assumeTrue("IGNORE", System.getProperty("some.property", "FOO").equals("BAR"));
                    }
                };
            }

            return base;
        }
    }
}

´´´

**Comment by laurilehmijoki** [comment]
The issue is now fixed, here's the commit: https://github.com/havarunner/havarunner/commit/2b517f03e22a01a0b6d029612a6b0747a213b269.

The problem was rather simple. HavaRunner just did not pass the annotations to JUnit. Now it does. 

Please let me know how the fix works for you. It is released in the version **1.2.1**.

**Comment by niom** [comment]
Thanks for the fix. Confirmed working.
